openapi: 3.0.0
info:
  title: Reference Manager API
  version: 1.0.0

paths:
  /categories:
    get:
      summary: Get the full list of categories
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      summary: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: Category created successfully

  /categories/{id}:
    get:
      summary: Get a category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
    put:
      summary: Update a category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '200':
          description: Category updated successfully
    delete:
      summary: Delete a category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Category deleted successfully

  /categories/{id}/references:
    get:
      summary: Get references for a category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of references
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/Book'
                    - $ref: '#/components/schemas/Link'
                    - $ref: '#/components/schemas/Note'
    post:
      summary: Add a reference to a category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/BookInput'
                - $ref: '#/components/schemas/LinkInput'
                - $ref: '#/components/schemas/NoteInput'
      responses:
        '201':
          description: Reference added successfully

  /categories/{id}/references/{referenceId}:
    get:
      summary: Get a specific reference by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: referenceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single reference
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Book'
                  - $ref: '#/components/schemas/Link'
                  - $ref: '#/components/schemas/Note'
    put:
      summary: Update a reference by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: referenceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/BookInput'
                - $ref: '#/components/schemas/LinkInput'
                - $ref: '#/components/schemas/NoteInput'
      responses:
        '200':
          description: Reference updated successfully
    delete:
      summary: Delete a reference by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: referenceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Reference deleted successfully

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    CategoryInput:
      type: object
      properties:
        name:
          type: string

    Book:
      type: object
      properties:
        type:
          type: string
        id:
          type: string
        title:
          type: string
        isbn:
          type: string
    BookInput:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        isbn:
          type: string

    Link:
      type: object
      properties:
        type:
          type: string
        id:
          type: string
        title:
          type: string
        url:
          type: string
        description:
          type: string
    LinkInput:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        url:
          type: string
        description:
          type: string
    Note:
      type: object
      properties:
        type:
          type: string
        id:
          type: string
        title:
          type: string
        text:
          type: string
    NoteInput:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        text:
          type: string
